### ISSUE TITLE
agent 기동시 에러 문의

### ISSUE THREAD

**Issue by defresh** [scouter-project/scouter#159]
안녕하세요.
우선 좋은 플랫폼 제공해주셔서 정말 감사드립니다 ( _ _)

scouter를 서비스중인 tomcat 에 적용을 해보고 있는데 agent 에서 아래와 같이 에러가 발생해서 문의 드립니다.

설치는 우선 document 및 quick start 있는 내용으로 설치를 했고.
현재 서비스중인 tomcat (jdk1.8 / tomcat7) 환경에서 java_opt 옵션에 agent 를 추가 해서 사용 해봤습니다.
다행이 데이터도 전송도 되고 client 에서 데이터 확인도 되는데
서버 기동 및 주기적으로 아래와 같이 에러가 발생 합니다^^;

java.lang.ArrayIndexOutOfBoundsException: 1
        at scouter.agent.counter.task.TomcatJMXPerf.getContextList(TomcatJMXPerf.java:157)
        at scouter.agent.counter.task.TomcatJMXPerf.process(TomcatJMXPerf.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scouter.agent.counter.CounterExecutingManager$Invocation.process(CounterExecutingManager.java:92)
        at scouter.agent.counter.CounterExecutingManager.run(CounterExecutingManager.java:57)

혹시 어떤 부분을 좀 확인 해 보면 좋을지 조언 부탁 드립니다.

감사합니다.

**Comment by bill23-kim** [comment]
Scouter 버전은 어떤걸 사용하신건가요?

**Comment by defresh** [comment]
오늘자 버전 받아서 테스트 했습니다~

**Comment by bill23-kim** [comment]
demo 안에있는 agent 말고 release 에 있는 latest 버전을 다운받아 해보시길 권해드립니다. Server와 클라이언트도 같은 버전으로 맞춰주시구요~

**Comment by defresh** [comment]
방금 시도해 봤는데 동일 하네요 ㅠ.ㅜ

  ____                  _
 / ___|  ___ ___  _   _| |_ ___ _ __
 \___ \ / __/   \| | | | __/ _ \ '__|
  ___) | (_| (+) | |_| | ||  __/ |
 |____/ \___\___/ \__,_|\__\___|_|
 Open Source S/W Performance Monitoring
 Scouter version 0.4.12 20160502

20160509 14:01:32 [SCOUTER] loaded by system classloader
20160509 14:01:32 [SCOUTER] Version 0.4.12 20160502
20160509 14:01:32 [SCOUTER] jar:file:/home/webroot/scouter/scouter/agent.java/scouter.agent.jar
20160509 14:01:32 [SCOUTER] objType:tomcat
20160509 14:01:32 [SCOUTER] objName:/testserver.net/DevBenefitUi
20160509 14:01:32 [A113] Counter Collector Started (#15)
20160509 14:01:32 [SCOUTER] Configure -Dscouter.config=./scouter.conf
20160509 14:01:32 [A100] agent boot seed=xdgi9u8ias
5ì›” 09, 2016 2:01:32 ì˜¤í›„ org.apache.catalina.core.StandardHost setAppBase
ê²½ê³ : Using an empty string for appBase on host [localhost] will set it to CATALINA_BASE, which is a bad idea
5ì›” 09, 2016 2:01:32 ì˜¤í›„ org.apache.tomcat.util.digester.SetPropertiesRule begin
ê²½ê³ : [SetPropertiesRule]{Server/Service/Engine/Host} Setting property 'xmlValidation' to 'false' did not find a matching property.
5ì›” 09, 2016 2:01:32 ì˜¤í›„ org.apache.tomcat.util.digester.SetPropertiesRule begin
ê²½ê³ : [SetPropertiesRule]{Server/Service/Engine/Host} Setting property 'xmlNamespaceAware' to 'false' did not find a matching property.
5ì›” 09, 2016 2:01:32 ì˜¤í›„ org.apache.catalina.core.AprLifecycleListener lifecycleEvent
ì •ë³´: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
5ì›” 09, 2016 2:01:33 ì˜¤í›„ org.apache.coyote.AbstractProtocol init
ì •ë³´: Initializing ProtocolHandler ["http-bio-9126"]
5ì›” 09, 2016 2:01:33 ì˜¤í›„ org.apache.catalina.startup.Catalina load
ì •ë³´: Initialization processed in 556 ms
5ì›” 09, 2016 2:01:33 ì˜¤í›„ org.apache.catalina.core.StandardService startInternal
ì •ë³´: Starting service Catalina
5ì›” 09, 2016 2:01:33 ì˜¤í›„ org.apache.catalina.core.StandardEngine startInternal
ì •ë³´: Starting Servlet Engine: Tbox
20160509 14:01:33 [A119] Agent UDP local.port=0
java.lang.ArrayIndexOutOfBoundsException: 1
        at scouter.agent.counter.task.TomcatJMXPerf.getMBeanList(TomcatJMXPerf.java:155)
        at scouter.agent.counter.task.TomcatJMXPerf.process(TomcatJMXPerf.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scouter.agent.counter.CounterExecutingManager$Invocation.process(CounterExecutingManager.java:92)
        at scouter.agent.counter.CounterExecutingManager.run(CounterExecutingManager.java:57)


참 client 에서 보면 항상 objects 란에 0cnt 로만 나옵니다.
Xlog 나 TPS 같은것들은 다 정상적이고요.

**Comment by bill23-kim** [comment]
Tomcat의 MBean 환경이 지금까지 본것과 조금 다른것 같습니다. 로그에 떨어지는 해당 익셉션은 아마 서버기동 후 시간이 조금 지나면 더이상 나오지 않을 것입니다. jconsole.exe 같은 툴로 MBean 을 볼수 있으시면 ObjectName 이 Catalina:type=Server 라는 빈의 Attribute 중 serverInfo 라는 키의 값이 뭔지 알려주실수 있을까요?
objects 의 0cnt 는 그 순간 워킹중인 스레드 숫자로 위 exception 과는 무관합니다.

**Comment by defresh** [comment]
확인해 봤는데 serverInfo 값은 Tbox 입니다.
톰캣 패키징이 약간 커스터마이징이 되어있다고 합니다.

뭐가 변경된건지 좀 확인해 보겠습니다 ( _ _)

**Comment by defresh** [comment]
힌트 주신 덕분에 해결했습니다^^
잘 사용하겠습니다 ( _ _)

**Comment by bill23-kim** [comment]
넵 감사합니다.
