### ISSUE TITLE
Can't start scouter server

### ISSUE THREAD

**Issue by jaxkodex** [scouter-project/scouter#19]
Hello, i am trying to start the server on ubuntu from the release version 0.2.5 but i am stuck with this error. i don't know what i am missing.

Thanks.
```
./startup.sh 
  ____                  _            
 / ___|  ___ ___  _   _| |_ ___ _ __ 
 \___ \ / __/   \| | | | __/ _ \ '__|
  ___) | (_| (+) | |_| | ||  __/ |   
 |____/ \___\___/ \__,_|\__\___|_|                                      
 Open Source S/W Performance Monitoring  
 Scouter version 0.2.5 20150730
 
20150731 10:50:45 Scouter Server Version 0.2.5 20150730
java.lang.NullPointerException
	at scouter.util.logo.Logo.print(Logo.java:67)
	at scouter.server.Main.main(Main.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scouter.boot.Boot.main(Boot.java:45)
java -cp ./boot.jar scouter.boot.Boot [./lib] 
Exception in thread "main" java.io.IOException: No existe el archivo o el directorio
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at scouter.server.db.DBCtr$.createLock(DBCtr.scala:53)
	at scouter.server.db.DBCtr.createLock(DBCtr.scala)
	at scouter.server.Main.main(Main.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scouter.boot.Boot.main(Boot.java:45)
```

**Comment by skyworker** [comment]
1. Please check the permission
   When the server start make a new file to make a db lock

**Comment by skyworker** [comment]
Let's me know which version of JDK you use!

**Comment by jaxkodex** [comment]
My JDK version 1.7.0_79

I changed the ownership from (501:staff, i don't know why it came like that) to my user and my group and it worked, i got the following

```
./startup.sh 
  ____                  _            
 / ___|  ___ ___  _   _| |_ ___ _ __ 
 \___ \ / __/   \| | | | __/ _ \ '__|
  ___) | (_| (+) | |_| | ||  __/ |   
 |____/ \___\___/ \__,_|\__\___|_|                                      
 Open Source S/W Performance Monitoring  
 Scouter version 0.2.5 20150730
 
System JRE version : 1.7.0_79

```

It didn't show the GeoLite warn, that is shown in https://github.com/scouter-project/scouter/wiki/Getting-Started thought.

Thanks

**Comment by skyworker** [comment]
Sorry I have hidden the log. Please ignore it.

Thanks.
