### ISSUE TITLE
OutOfMemoryError 제보드립니다.

### ISSUE THREAD

**Issue by traeper** [scouter-project/scouter#229]
안녕하세요. 
스카우터 이용 중에 버그를 발견하여 제보드립니다.
## 테스트 시나리오
- 공지사항 admin 로그인

->로그인 실패 - 원인 : network connection failed.
- 서버에 접속해서 TCP 커넥션을 확인.

-> Agent가 20~30개는 되는데, 커넥션이 2개만 ESTABLISHED.
- 서버 재시작

-> 정상 가동(로그인 가능해짐.)
## 로그 확인

```
/.. Cannot find a tcp agent for ~ many instance ../ 
20160819 00:00:02 [S501] Cannot find a tcp agent for /.../.../ajp-bio-6001
20160819 00:00:10 [S133] java.io.FileNotFoundException: ./database/20160819/counter/real.data (No such file or directory)
20160819 00:00:10 [S143] can't open
20160819 00:00:10 [S122] can't open db
20160819 00:00:10 [G103] ./database/20160819/counter/5m.kfile (No such file or directory)
20160819 00:00:10 [G104] java.io.FileNotFoundException: ./database/20160819/counter/5m.kfile (No such file or directory)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
        at scouter.server.db.io.RealKeyFile.<init>(RealKeyFile.scala:37)
        at scouter.server.db.io.IndexKeyFile.<init>(IndexKeyFile.scala:39)
        at scouter.server.db.counter.DailyCounterIndex.<init>(DailyCounterIndex.scala:48)
        at scouter.server.db.counter.DailyCounterIndex$.open(DailyCounterIndex.scala:37)
        at scouter.server.db.DailyCounterWR$.open(DailyCounterWR.scala:122)
        at scouter.server.db.DailyCounterWR$$anonfun$1.apply$mcV$sp(DailyCounterWR.scala:50)
        at scouter.server.util.ThreadScala$$anon$4.run(ThreadScala.scala:61)
```

위의 FileNotFoundException 로그가 무수히 찍히다가 결국엔...

```
20160822 00:03:00 [S122] can't open db
20160822 00:04:00 [G103] Java heap space
20160822 00:04:00 [G104] java.lang.OutOfMemoryError: Java heap space
```

OOM이 발생하면서 프로세스가 제대로 동작하지 않는 현상이 발생했습니다.

**Comment by gunlee01** [comment]
제보 감사합니다.

**Comment by gunlee01** [comment]
fail to reissue
