### ISSUE TITLE
Client can't launch in macOS Sierra

### ISSUE THREAD

**Issue by bill23-kim** [scouter-project/scouter#231]
!SESSION 2016-09-26 09:44:53.343 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=ko_KR
Framework arguments:  -keyring /Users/bill23/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/bill23/.eclipse_keyring -showlocation

!ENTRY org.eclipse.osgi 4 0 2016-09-26 09:44:54.590
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: The platform metadata area could not be written: /private/var/folders/h9/qt1grktd6j3frwtjrh9s_jv40000gp/T/AppTranslocation/F908A5B2-629A-4386-8FA2-9D84DBE40A08/d/scouter.client.app/Contents/MacOS/workspace/.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.
    at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:61)
    at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:129)
    at org.eclipse.core.internal.preferences.InstancePreferences.getBaseLocation(InstancePreferences.java:44)
    at org.eclipse.core.internal.preferences.InstancePreferences.initializeChildren(InstancePreferences.java:199)
    at org.eclipse.core.internal.preferences.InstancePreferences.<init>(InstancePreferences.java:59)
    at org.eclipse.core.internal.preferences.InstancePreferences.internalCreate(InstancePreferences.java:209)
    at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:391)
    at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:379)
    at org.eclipse.core.internal.preferences.PreferencesService.createNode(PreferencesService.java:389)
    at org.eclipse.core.internal.preferences.RootPreferences.getChild(RootPreferences.java:63)
    at org.eclipse.core.internal.preferences.RootPreferences.getNode(RootPreferences.java:101)
    at org.eclipse.core.internal.preferences.RootPreferences.node(RootPreferences.java:90)
    at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:38)
    at org.eclipse.core.runtime.preferences.InstanceScope.getNode(InstanceScope.java:80)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.getStorePreferences(ScopedPreferenceStore.java:229)
    at org.eclipse.ui.preferences.ScopedPreferenceStore.<init>(ScopedPreferenceStore.java:133)
    at org.eclipse.ui.plugin.AbstractUIPlugin.getPreferenceStore(AbstractUIPlugin.java:288)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:620)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at scouter.client.Application.start(Application.java:34)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

**Comment by bananayong** [comment]
need to put eclipse option in scouter.ini (or scouter.client.product for build)
-data
/tmp (for example)

cc. @bill23-kim 

reference: https://www.eclipse.org/forums/index.php/t/214452/

**Comment by bill23-kim** [comment]
Thank you!! As you advice I committed. [commit](https://github.com/scouter-project/scouter/commit/ff55a68615c9a06ec040d62eca0536ad17123ecc)

**Comment by louiegit** [comment]
!SESSION 2017-11-21 01:11:49.358 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=zh_CN
Framework arguments:  -keyring /Users/louie/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data ~/my_workspace -keyring /Users/louie/.eclipse_keyring -showlocation

!ENTRY org.eclipse.osgi 4 0 2017-11-21 01:11:52.271
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: The platform metadata area could not be written: /private/var/folders/9g/50702tws511br6t4gw2wgmfr0000gn/T/AppTranslocation/D98D1F72-F5C9-451B-835A-D9869E41C754/d/mat.app/Contents/MacOS/~/my_workspace/.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.

**Comment by louiegit** [comment]
I use -data parameter .But it doesn't work.Is there any wrong usage?

**Comment by bill23-kim** [comment]
@louiegit i recommend you to use latest version [https://github.com/scouter-project/scouter/releases/download/v1.8.0/scouter.client.product-macosx.cocoa.x86_64.tar.gz](https://github.com/scouter-project/scouter/releases/download/v1.8.0/scouter.client.product-macosx.cocoa.x86_64.tar.gz)
it included those parameters by default.

**Comment by sushil1992** [comment]
It worked if I moved the application from the Downdload folder to the Applications folder.
