### ISSUE TITLE
Weblogic - DB2  에서 procedure 호출 시 오류 문의

### ISSUE THREAD

**Issue by lim0818** [scouter-project/scouter#251]
안녕하세요.
weblogic - DB2(9.7) 환경에서 다른 건 다 모니터링 되는데
db Procedure 호출시에믄 해당 쓰레드/트랜젝션 수행 오류가 발생 됩니다.
혹, procedure 호출관련 부분만  scouter 에서 관여하지 않토록 설정 하는 방법이 있을 까요?

**Comment by sjokim** [comment]
DB2 드라이버는 난독 처리가 되어있어 hooking이 아닌 Wrapper 를 통해서 SQL을 추적합니다. 
그래서 다른 드라이버와 수집방식이 다른데요.. CallableStatement만 off하는 옵션은 현재는 없습니다.
JDK버전과 에러 메세지를 상세하게 올려 주시면 수정에 도움이 될것 같습니다. 

그리고 급하시면  에이전트 코드에서
scouter.agent.java 프로젝트에 
scouter.jdbc.WrConnection에서 아래 메소드를 의 리턴을 수정하시고 직접 빌드하시면 될 것 같습니다..

final public java.sql.CallableStatement prepareCall(java.lang.String a0) throws java.sql.SQLException {
		return new WrCallableStatement(this.inner.prepareCall(a0), a0);
       --> return this.inner.prepareCall(a0);
	}

	final public java.sql.CallableStatement prepareCall(java.lang.String a0, int a1, int a2)
			throws java.sql.SQLException {
		return new WrCallableStatement(this.inner.prepareCall(a0, a1, a2), a0);
   --> return this.inner.prepareCall(a0,a1,a2);

	}

	final public java.sql.CallableStatement prepareCall(java.lang.String a0, int a1, int a2, int a3)
			throws java.sql.SQLException {
		return new WrCallableStatement(this.inner.prepareCall(a0, a1, a2, a3), a0);
   --> return this.inner.prepareCall(a0,a1,a2,a3);
	}

감사합니다.

**Comment by lim0818** [comment]
감사합니다. 
가이드 주신데로 컴파일 하여 테스트 해 보도록 하겠습니다.
참고로 해당 오류 발생시 아래 처럼 로그가 찍혔었습니다.
(참고로 AIX6/IBM JDK6(64bit), IBM DB2 9.7 환경에  middleware는 weblogic 10.x 환경입니다.)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OOO_DEVICE_MOVE_SP_STOCK_STORED_PROCEDURE   { CALL OOO.IV_STOCK_MOVE_DM('~~~)
위 처럼 프로시저 호출 싯점 아래 와 같은 로그가 발생 됩니다.

<BEA-000000> <java.sql.SQLException: getMetaData, Exception = null>                                                                                  
<BEA-000000> <at weblogic.jdbc.wrapper.ResultSet.getMetaData(ResultSet.java:256)>                                                                    
<BEA-000000> <at com.xxx.framework.aop.ExeMetaDataAspectJ.ajc$before$com_abc_aop_ExeMetaDataAspectJ$1$d163ffc2(ExeMetaDataAspectJ.aj:25)>
<BEA-000000> <at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleResults(SqlExecutor.java:358)>                                                 
<BEA-000000> <at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleMultipleResults(SqlExecutor.java:295)>                                         
<BEA-000000> <at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQueryProcedure(SqlExecutor.java:277)>                                         
<BEA-000000> <at com.ibatis.sqlmap.engine.mapping.statement.ProcedureStatement.sqlExecuteQuery(ProcedureStatement.java:34)>                          
<BEA-000000> <at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryWithCallback(GeneralStatement.java:179)>                    
<BEA-000000> <at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryForObject(GeneralStatement.java:105)>                       
<BEA-000000> <at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:582)>                               
<BEA-000000> <at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:557)>                               
<BEA-000000> <at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)>                                         
<BEA-000000> <at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForObject(SqlMapClientImpl.java:83)>                                            
<BEA-000000> <at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)>                                                                      
<BEA-000000> <at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)>                                              
<BEA-000000> <at com.xxx.xx.dao.inventory.DeviceMovePDADAO.callStoredProcedure(DeviceMovePDADAO.java:98)>                                       
<BEA-000000> <at com.xxx.xxs.service.inventory.DeviceMovePDAService.performCommit(DeviceMovePDAService.java:876)>                                
<BEA-000000> <at com.xxx.xx.framework.core.ExeTransactionCtr.doRequest(ExeTransactionCtr.java:24)>                                                     
<BEA-000000> <at com.xxx.xx.framework.core.ExeBaseCtr.handleRequest(ExeBaseCtr.java:97)>                                                               
<BEA-000000> <at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)>                                           
<BEA-000000> <at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:511)>                                                 
<BEA-000000> <at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)>                                                                       
<BEA-000000> <at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)>                                 
<BEA-000000> <at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:300)>                                                        
<BEA-000000> <at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3717)>                     
<BEA-000000> <at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)>                                            
<BEA-000000> <at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)>                                                          
<BEA-000000> <at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1454)>                                                     
<BEA-000000> <at weblogic.work.ExecuteThread.run(ExecuteThread.java:178)>

**Comment by sjokim** [comment]
답변이 늦었습니다. 
보통 윕로직은 Wrapper를 자동으로 generate해서 사용합니다.
그러다보니 원래 예상한 드라이버와 다른 Wrapper가 나타나면 오동작하는 경우가 있는데 
DB2의 경우에는 대부분의 클래스가 난독 처리되어있어 Injection 방식으로 SQL추적하는데 어려움이 있습니다.
 하지만 오류가 리포팅되었으니 DB2드라이버에 대해서도 injection방식으로 SQL을 추적하는 방안을
연구해봐야할것 같습니다. 
일단 Workaround로 처음 가이드 드린데로 적용해 보시기 바랍니다.
