### ISSUE TITLE
java.lang.NumberFormatException: For input string: "2147484142" 오류 문의 드립니다.

### ISSUE THREAD

**Issue by rindol** [scouter-project/scouter#318]
훌륭한 Scouter를 배포해 주셔서 유용하게 사용하고 있음에 항상 감사한 마음을 가지고 있습니다.
잘 사용하던 도중 아래와 같이 오류가 발생하여 확인 가능한지 여쭙고자 글 남겨드리니 확인 부탁 드립니다.

For input string 이후에 나온 2147484142를 Int형으로 변환하다가 범위에 벗어나서 exception이 발생한 것 같은데, 정확히 모르겠어서요.
----------------------------
```18:17:42,924 ERROR [stderr] (Scouter-CounterExecutingManager) java.lang.NumberFormatException: For input string: "2147484142"
18:17:42,925 ERROR [stderr] (Scouter-CounterExecutingManager)   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
18:17:42,926 ERROR [stderr] (Scouter-CounterExecutingManager)   at java.lang.Integer.parseInt(Integer.java:495)
18:17:42,926 ERROR [stderr] (Scouter-CounterExecutingManager)   at java.lang.Integer.parseInt(Integer.java:527)
18:17:42,927 ERROR [stderr] (Scouter-CounterExecutingManager)   at org.jboss.dmr.StringModelValue.asInt(StringModelValue.java:61)
18:17:42,927 ERROR [stderr] (Scouter-CounterExecutingManager)   at org.jboss.dmr.ModelNode.asInt(ModelNode.java:226)
18:17:42,928 ERROR [stderr] (Scouter-CounterExecutingManager)   at org.jboss.as.jmx.model.TypeConverter$IntegerTypeConverter.fromModelNode(TypeConverter.java:303)
18:17:42,928 ERROR [stderr] (Scouter-CounterExecutingManager)   at org.jboss.as.jmx.model.TypeConverter.fromModelNode(TypeConverter.java:83)
18:17:42,929 ERROR [stderr] (Scouter-CounterExecutingManager)   at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:220)
18:17:42,930 ERROR [stderr] (Scouter-CounterExecutingManager)   at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:181)
18:17:42,930 ERROR [stderr] (Scouter-CounterExecutingManager)   at org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.getAttribute(ModelControllerMBeanServerPlugin.java:69)
18:17:42,931 ERROR [stderr] (Scouter-CounterExecutingManager)   at org.jboss.as.jmx.PluggableMBeanServerImpl.getAttribute(PluggableMBeanServerImpl.java:154)
18:17:42,932 ERROR [stderr] (Scouter-CounterExecutingManager)   at scouter.agent.counter.task.JBossJMXPerf.process(JBossJMXPerf.java:129)
18:17:42,933 ERROR [stderr] (Scouter-CounterExecutingManager)   at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
18:17:42,933 ERROR [stderr] (Scouter-CounterExecutingManager)   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:17:42,934 ERROR [stderr] (Scouter-CounterExecutingManager)   at java.lang.reflect.Method.invoke(Method.java:606)
18:17:42,934 ERROR [stderr] (Scouter-CounterExecutingManager)   at scouter.agent.counter.CounterExecutingManager$Invocation.process(CounterExecutingManager.java:92)
18:17:42,935 ERROR [stderr] (Scouter-CounterExecutingManager)   at scouter.agent.counter.CounterExecutingManager.run(CounterExecutingManager.java:57)```

**Comment by bill23-kim** [comment]
에이전트 버전은 어떤걸 사용하고 계신가요?

**Comment by rindol** [comment]
agent 버전을 확인하는 법을 정확히 알지 못하여 agent jar 내 포함되어 있는 버전 정보 전달 드립니다.

#Scouter Version
#Sun, 15 May 2016 17:23:37 +0900

VERSION=0.4.13
BUILD=20160515

**Comment by bill23-kim** [comment]
같은 이슈 제기가 올해 3월쯤 있었고
원인과 현상은 아래와 같았습니다.
~~~
jboss 의 jmx 를 통해 꺼내오는 값중 어떤 값이 integer 의 max 값을 벗어났는데 jboss 내부적으로 parseInt 를 하다가 난 익셉션이 난거 같네요.. (bytesReceived 혹은 bytesSent 으로 추정...) 인스턴스가 올라올때 처음부터 났던 exception 이라면 scouter 가 수집을 중지 하는데 중간부터 나기 시작할때는 계속 시도하고 exception 로그를 찍도록 되어 있는것 같습니다.. (2초마다)
~~~
그래서 그 이후 버전에 위와 같은 에러가 발생하면 그 항목에 대해서는 다시 수집 하지 않도록 수정 되었습니다. v0.5.1 교체하시면 주기적인 에러로그는 멈출것으로 예상됩니다.
