### ISSUE TITLE
[RFE] Scouter Docker Version

### ISSUE THREAD

**Issue by Jooho** [scouter-project/scouter#360]
안녕하세요.

아직 Scouter Docker Version이 없는 것 같아서 한번 만들어 봤습니다.

크게 Docker 엔진에서 디플로이 하는 방식과 Openshift위에서 디플로이 하는 방식 2가지 입니다.

Github URL은 아래와 같습니다.
https://github.com/Jooho/scouter-docker

테스트는 아래의 시스템에서 해보았습니다.
**docker version**
~~~
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
~~~
**OpenShift**
~~~
Openshift Container Platform 3.5
~~~

아래이미지는 Openshift에서 실행했을때입니다.
![openshift](https://user-images.githubusercontent.com/2375181/29630469-5d135aa0-880a-11e7-9872-b0cb196eaeb4.png)

그런데 agent.java에서 hostname 명령어를 사용하는지 에러가 나네요.
~~~
java.io.IOException: Cannot run program "hostname": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at scouter.util.SysJMX.getHostName(SysJMX.java:181)
	at scouter.agent.Configure.resetObjInfo(Configure.java:1121)
	at scouter.agent.Configure.apply(Configure.java:1013)
	at scouter.agent.Configure.reload(Configure.java:707)
	at scouter.agent.Configure.<init>(Configure.java:654)
	at scouter.agent.Configure.getInstance(Configure.java:74)
	at scouter.agent.AgentTransformer.<clinit>(AgentTransformer.java:48)
	at scouter.agent.JavaAgent.premain(JavaAgent.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 17 more
~~~

**Comment by gunlee01** [comment]
멋지네요.
scouter에서 hostname 명령어는 host agent의 이름을 정하거나 java agent에서 매핑되는 host agent를 찾기위해서 사용됩니다.
docker 환경에서 hostname 명령어가 없는 이유가 있나요?

**Comment by Jooho** [comment]
확인을 해보니깐... Centos나 Fedora/ Debian 같은 OS는 hostname package가 설치가 되어 있는데 RHEL 이미지는  설치가 되어 있지 않네요.. 하지만  모두 HOSTNAME이라는 Environment Variable가 존재하네요. 

따라서 centos기반인 pure docker test app은 문제가 없는데 RHEL기반인 openshift test app은 문제가 있네요.

이것은 어떤 Base 이미지를 사용하느냐 따라 어떤 패키지가 설치 되어 있는가의 문제네요. agent에 hostname 명령어가 없을 경우 Environment Variable을 읽도록 하는 로직을 넣는 것이 어떨까요?

**Comment by bill23-kim** [comment]
hostname 명령이 없을 경우 아래와 같이 뽑고 있습니다. 
~~~
RuntimeMXBean o = ManagementFactory.getRuntimeMXBean();
String nm = o.getName();
int x = nm.indexOf("@");
hostname = nm.substring(x + 1);
~~~
에러메세지는 catch 안에서 뿌려주는거라 상관없을것 같아요.

**Comment by Jooho** [comment]
네 맞아요. 에러가 사실 문제는 안되지만... 사용자 관점에서 에러를 보고 싶어하지 않을테니.. trace로그레벨로 해당 메시지를 올리거나 해서 실제적으로 stdout로 안보이게 하면 좋을거 같아요 .

**Comment by bill23-kim** [comment]
@Jooho 
넵. 그렇게 해야겠네요. 감사합니다.
