### ISSUE TITLE
java9 에서 실행 오류

### ISSUE THREAD

**Issue by 23king** [scouter-project/scouter#367]
!SESSION 2017-09-27 17:36:30.515 -----------------------------------------------
eclipse.buildId=unknown
java.version=9
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=ko_KR
Framework arguments:  -keyring /Users/1002353/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data @user.home/.scouter -keyring /Users/1002353/.eclipse_keyring

!ENTRY org.eclipse.osgi 4 0 2017-09-27 17:36:43.789
!MESSAGE Application error
!STACK 1
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)
        at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:294)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:490)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:504)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:203)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:632)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at scouter.client.Application.createAndRunWorkbench(Application.java:143)
        at scouter.client.Application.start(Application.java:73)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by bill23-kim** [comment]
이클립스에서 바로 실행시킬때 오류인가요?
아니면 릴리즈 버전 오류인가요?

**Comment by bill23-kim** [comment]
일단 임시 방편으로는 
scouter.client.app/Contents/Eclipse/scouter.ini 파일을 열어서
-vmargs 밑에 아래 옵션을 추가해주세요. 다음 릴리즈때 수정 되도록 하겠습니다.

~~~
--add-modules=java.se.ee
~~~

**Comment by 23king** [comment]
릴리즈버젼의 오류였어요 ㅠㅠ

**Comment by gunlee01** [comment]
resolved at v1.8.0
