### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by sohwaje** [scouter-project/scouter#497]
JDK 1.7 사용하고 있습니다.

scouter server를 기동하기 위해 ./startup.sh를 실행하면 아래와 같은 에러가 발생합니다. 
./startup.sh
nohup: redirecting stderr to stdout
Exception in thread "main" java.lang.UnsupportedClassVersionError: scouter/boot/Boot : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by gaiajeon** [comment]
Unsupported major.minor version 52.
1.8로 컴파일된 클래스를 더 낮은 버젼에서 실행할때 나오는 에러 입니다.
JDK1.8로 실행하셔야 하네요

**Comment by sohwaje** [comment]
어플리케이션이  jdk1.7 환경에서 개발된 것이라 그런가 봅니다.
그럼 어플리케이션은 그대로 1.7을 쓰고 scouter만 jdk1.8 환경에서 구동할 수 있을까요?

**Comment by gaiajeon** [comment]
scouter server만 1.8로 실행하시고 기존 어플리케이션은 개발버젼 그대로 구동하시면 됩니다.
제가 스크립트 내용을 안봐서 자세히 모르겠지만
실행 스크립트에서 JAVA_HOME을 설정하거나 실행 java 경로를 full path로 선언해주면 됩니다.
