### ISSUE TITLE
WEB API 사용시 Socket 에러

### ISSUE THREAD

**Issue by mavreiq80** [scouter-project/scouter#528]
WEB API를 사용하여 xlog를 수집하고 있습니다. 아래와 같이 socket 오류가 발생하여 정상적으로 데이터를 수집하지 못하는 경우들이 발생하고 있는데요. 다시 데이터를 요청하면 정상적으로 데이터를 수집합니다.  상세한 로그는 아래와 같습니다.

1. 요청시 500 에러 발생
xxx.xx.xxx.xx - - [26/Nov/2018:13:02:51 +0900] "GET /scouter/v1/xlog-data/20181126?startHms=124946&endHms=125046&objHashes=-1282738849,598933410,-998721948,1602799821,1832032417,1358983967,-1494619128,1665644874,1540754279,-5
88823600,-170356316,-1166965571,1134972384,-197408485,-1010576331,-1389244758,267240384,1975733867,-1957448571,-1318077871,1075178457,595121415,-1015390012,-1853270429,280028613,-605710992,1562211861 HTTP/1.1" 500 258 "-" "M
ozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"

2. 로그에서 Socket Exception 발생
 13:02:44.118 [XLogThread-127.0.0.1:6100-0]  INFO  s.w.framework.client.net.TcpProxy[58] - TcpProxy created : pool-size:0, scouterx.webapp.framework.client.net.TcpProxy@2001cca3
 13:02:44.119 [XLogThread-127.0.0.1:6100-0]  INFO  s.w.framework.client.net.ClientTCP[62] - Connected scouterx.webapp.framework.client.net.ClientTCP@ee8eea4f to 127.0.0.1:6100
#ort4796 13:02:51.097 [qtp1119901080-1184]  INFO  s.w.framework.client.net.TcpProxy[110] - TcpProxy closed : pool-size:7, scouterx.webapp.framework.client.net.TcpProxy@4bc5295c, stack:
#ort4796 13:02:51.098 [qtp1119901080-1184]  ERROR s.w.f.e.m.GenericExceptionMapper[66] - [WebApplicationException] 500 - java.net.SocketException: A system call received a parameter that is not valid. (Read failed) [caused b
y] A system call received a parameter that is not valid. (Read failed), [uri]v1/xlog-data/20181126
java.lang.RuntimeException: java.net.SocketException: A system call received a parameter that is not valid. (Read failed)
        at scouterx.webapp.framework.client.net.TcpProxy.process(TcpProxy.java:206)
        at scouterx.webapp.layer.consumer.XLogConsumer.handlePageableXLog(XLogConsumer.java:108)
        at scouterx.webapp.layer.service.XLogService.handlePageableXLog(XLogService.java:56)
        at scouterx.webapp.layer.controller.XLogDataController.lambda$streamPageableXLog$2(XLogDataController.java:166)
        at scouterx.webapp.layer.controller.XLogDataController$$Lambda$35.39382750.accept(Unknown Source)
        at scouterx.webapp.view.CommonResultView.jsonStream(CommonResultView.java:120)
        at scouterx.webapp.layer.controller.XLogDataController.lambda$streamPageableXLog$3(XLogDataController.java:174)
        at scouterx.webapp.layer.controller.XLogDataController$$Lambda$36.35F5F470.write(Unknown Source)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:78)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:60)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at scouterx.webapp.framework.filter.ReleaseResourceFilter.doFilter(ReleaseResourceFilter.java:44)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at scouterx.webapp.framework.filter.NoCacheFilter.doFilter(NoCacheFilter.java:40)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at scouterx.webapp.framework.filter.CorsFilter.doFilter(CorsFilter.java:65)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)

**Comment by gunlee01** [comment]
`java.net.SocketException: A system call received a parameter that is not valid. (Read failed)`
라면 여러가지 가능성을 좀 확인해봐야 할 것 같습니다.
데모 환경에서 재현이 가능하면 좋을텐데 좀 애매하네요.

**Comment by gunlee01** [comment]
어플리케이션에서 발생하는 문제가 아닐수도 있을 것 같습니다.
중간에 경유하는 네트워크 장비등에서 일정 시간이 지난 socket을 끊는게 아닌지 확인해보시기 바랍니다.
