### ISSUE TITLE
Can't start scouter server on jdk 1.7

### ISSUE THREAD

**Issue by aldiyudhaa** [scouter-project/scouter#556]
Hi, i can't start scouter server.
Here is the error message :
Exception in thread "main" java.lang.UnsupportedClassVersionError: scouter/boot/                                                                             Boot : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)                                                                       
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

any solution for this? i've search on google and i found the problem is scouter server has compile on jdk 1.8+ but my server use jdk 1.7
i use Red hat enterprise linux as operating system.

Thank you.
Best regards, 
Aldi Yudha Pradipta

**Comment by gunlee01** [comment]
Scouter server only support JDK8+. But an agent JDK6+.
Setup another JDK with 8+ for scouter collector server and modify startup.sh for the java path.

**Comment by aldiyudhaa** [comment]
Okay i see, but i use application in jboss and that application only can running in JDK7.
This scouter can monitoring another Java servlet application servers besides tomcat? because i use jboss. 

Thank you

**Comment by bill23-kim** [comment]
The scouter collector server is separate from your application server. Therefore, it is not related to the java version of your application.
