### ISSUE TITLE
이전 xlog의 profile 이 보이지 않는 문제

### ISSUE THREAD

**Issue by spc1jh** [scouter-project/scouter#559]
안녕하세요 scouter를 잘 이용중이며 버전은 2.6.0입니다. 
클라이언트를 통해 이전 상태의 xlog 및 profile을 보려고 하면 정상적으로 출력이 되지 않습니다. 
xlog는 정상적으로 나오나 상세 항목으로 들어가면 아래와 같은 메시지만 나오며 profile이 보이지 않습니다.  ( No xlog profile collected ) 
실시간 데이터나 금일 날짜의 데이터는 정상적으로 보입니다. 바로 전일것만 되도 보이지 않아서 확인 요청드립니다. 

아래와 같이 설정한 상태이며, 디스크 여유 공간은 있습니다. 

mgr_purge_disk_usage_pct=80
mgr_purge_profile_keep_days=20
mgr_purge_xlog_keep_days=30
mgr_purge_counter_keep_days=30

또한, 디스크를 보면 profile이 전일건 삭제가 됩니다. (xlog.profile.conf 만 남겨놓네요)
내용은 다음과 같습니다. 
-- listing properties --
compress_profile_enabled=false

**Comment by gunlee01** [comment]
00시 직전에 디스크를 얼마나쓰는지도 한번 확인해보시기 바랍니다.
하루치 데이터로 디스크 사용량이 80%가 넘어가는 경우일 수 있을 것 같네요.

**Comment by spc1jh** [comment]
만약 00시 기준으로 80%가 초과되어 데이터가를 삭제 하는 경우, 전일 데이터의 profile 부터 삭제 되는게 맞는건가요?
오래된 항목의 Xlog 등 다른 값들은 남아있는데 profile값들만 삭제되는게 궁금합니다. 
오래된 항목의 xlog등은 계속해서 존재합니다.

**Comment by spc1jh** [comment]
> 00시 직전에 디스크를 얼마나쓰는지도 한번 확인해보시기 바랍니다.
> 하루치 데이터로 디스크 사용량이 80%가 넘어가는 경우일 수 있을 것 같네요.

만약 00시 기준으로 80%가 초과되어 데이터가를 삭제 하는 경우, 전일 데이터의 profile 부터 삭제 되는게 맞는건가요?
오래된 항목의 Xlog 등 다른 값들은 남아있는데 profile값들만 삭제되는게 궁금합니다.
오래된 항목의 xlog등은 계속해서 존재합니다.

**Comment by gunlee01** [comment]
공간 확보를 위해서 프로파일을 먼저 삭제되도록 동작합니다.

**Comment by rusyasoft** [comment]
Scounter version (2.7.1)

저도 갑짜기 No xlog profile collected 나오고 있습니다. 지난번에도 나왔을때 서버들어가서 database 에 있는 날짜로 되 있는 folder 들은 삭재하고 서버를 재시작했을때 다시 보였거든요. 근데 지금은 저렇게 해결이 안되네요.

그리고요, 제가 scouter APM 에서 xlog 볼려고할때, server 에 있는 nohup.out 에서 아래 같은 오류가 나옵니다:

```
java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
	at scouter.io.DataInputX.<init>(DataInputX.java:46)
	at scouter.server.netio.service.handle.XLogService.getProfile(XLogService.scala:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scouter.server.netio.service.ServiceHandlingProxy$Invocation.exec(ServiceHandlingProxy.java:42)
	at scouter.server.netio.service.ServiceHandlingProxy.process(ServiceHandlingProxy.java:101)
	at scouter.server.netio.service.net.ServiceWorker.run(TcpServiceWorker.scala:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

어떻게 하면될까요 ?

**Comment by rusyasoft** [comment]
이상하네요, 날짜가 UTC 시간으로 00 시 넘었더니 다시 정상으로 나오네요

**Comment by bill23-kim** [comment]
@rusyasoft 
클라이언트와 서버의 타임존이 다르면 해당현상이 발생할 수 있습니다.
상황이 클라이언트의 타임존을 맞추시는게 맞을꺼 같애요. 

scouter.ini 
~~~
vmargs
-Duser.timezone="UTC"
~~~

를 설정해주세요

**Comment by bgrooot** [comment]
@bill23-kim 
OSX 환경에서 Scouter.client와 동일한 경로에 scouter.ini 파일이 있으면 될까요?

**Comment by bill23-kim** [comment]
@bgrooot 
macOS에서 scouter.ini 파일은 아래 경로에 이미 있습니다.
~~~
scouter.client.app/Contents/Eclipse/scouter.ini
~~~
vmargs 도 이미 다른 설정들이 많이 들어가있습니다. 거기에 -Duser.timezone 설정만 추가해주시면 되겠네요
