### ISSUE TITLE
500 NullPointerException

### ISSUE THREAD

**Issue by leedongwan** [scouter-project/scouter#573]
#pa64 15:17:48.775 [qtp289639718-21]  ERROR s.w.f.e.m.GenericExceptionMapper[66]
 - [WebApplicationException] 500 - null, [uri]v1/interactionCounter/realTime
java.lang.NullPointerException: null
        at scouterx.webapp.layer.consumer.CounterConsumer.retrieveRealTimeCounte
rsByObjTypeOrObjHashes(CounterConsumer.java:282)
        at scouterx.webapp.layer.consumer.CounterConsumer.retrieveRealTimeCounte
rsByObjHashes(CounterConsumer.java:74)
        at scouterx.webapp.layer.service.CounterService.retrieveRealTimeCounters
ByObjHashes(CounterService.java:49)
        at scouterx.webapp.layer.controller.InteractionCounterController.findHos
tCounters(InteractionCounterController.java:157)
        at scouterx.webapp.layer.controller.InteractionCounterController.retriev
eRealTimeCountersByObjHashes(InteractionCounterController.java:133)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHa
ndlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethod
Dispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethod
Dispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatch
erProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:2
43)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethod
Dispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(Resour
ceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(Resourc
eMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(Resourc
eMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:27
7)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(Request
Scope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:
256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHand
ler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.ja
va:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:3
70)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContaine
r.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContaine
r.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContaine
r.java:229)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841
)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1650)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(We
bSocketUpgradeFilter.java:206)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1637)
        at scouterx.webapp.framework.filter.ReleaseResourceFilter.doFilter(Relea
seResourceFilter.java:44)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1637)
        at scouterx.webapp.framework.filter.NoCacheFilter.doFilter(NoCacheFilter
.java:40)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1637)
        at scouterx.webapp.framework.filter.CorsFilter.doFilter(CorsFilter.java:
65)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1637)
        at scouterx.webapp.framework.filter.LoggingInitServletFilter.doFilter(Lo
ggingInitServletFilter.java:50)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1637)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandl
er.java:188)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandl
er.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandle
r.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandle
r.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.
java:521)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerColl
ection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.jav
a:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(Abstra
ctConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.jav
a:128)
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invo
cable.java:222)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWh
atYouKill.java:294)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouK
ill.java:199)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool
.java:591)
        at java.lang.Thread.run(Thread.java:748)

**Comment by gunlee01** [comment]
Got it. Let me check.
