### ISSUE TITLE
Getting issue in scouter-client source code while running the project.

### ISSUE THREAD

**Issue by samikshajha07** [scouter-project/scouter#697]
I am getting this issue.. Please help me

!SESSION 2020-05-13 12:12:59.574 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_251
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -product scouter.client.product
Command-line arguments:  -product scouter.client.product -data /Users/quantega/eclipse-workspace/../runtime-scouter.client.product -dev file:/Users/quantega/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/scouter.client.product/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog

!ENTRY org.eclipse.osgi 4 0 2020-05-13 12:13:02.935
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: scouter/util/StringUtil
	at scouter.client.preferences.ServerPrefUtil.getStoredServerList(ServerPrefUtil.java:78)
	at scouter.client.Application.loginAutomaticallyWhenAutoLoginEnabled(Application.java:103)
	at scouter.client.Application.start(Application.java:75)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: java.lang.ClassNotFoundException: scouter.util.StringUtil cannot be found by scouter.client_1.0.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 16 more
An error has occurred. See the log file
/Users/quantega/runtime-scouter.client.product/.metadata/.log.

**Comment by gunlee01** [comment]
which version of the client did you run?

**Comment by gunlee01** [comment]
If you try to run with source code, please run the build file before for creating some scouter common library dependencies `./build_package.sh`.
