### ISSUE TITLE
버전 업데이트후 xlog가 수집되지 않는것 같습니다..

### ISSUE THREAD

**Issue by lu8300test** [scouter-project/scouter#699]
was : tomcat7
scouter version  :  2.8.1

ㅁ스카우터 클라이언트 해서 xlog 볼경우 
 - No xlog profile collected )
ㅁ 서버 오류 로그 
 - java.lang.RuntimeException: Unknown pack type= 27
	at scouter.lang.pack.PackEnum.create(PackEnum.java:60)
	at scouter.io.DataInputX.readPack(DataInputX.java:268)
	at scouter.server.netio.data.NetDataProcessor$.processCafe(NetDataProcessor.scala:113)
	at scouter.server.netio.data.NetDataProcessor$.process(NetDataProcessor.scala:76)
	at scouter.server.netio.data.NetDataProcessor$$anonfun$1$$anonfun$apply$1.apply$mcV$sp(NetDataProcessor.scala:46)
	at scouter.server.util.ThreadScala$$anon$1.run(ThreadScala.scala:12)

**Comment by gunlee01** [comment]
안녕하세요.

collector server 버전은 java agent 버전과 같거나 더 상위 버전이어야 합니다.
2.8.1에 새롭게 정의된 pack type 27을 collector server가 파싱할 수 없어 발생하는 오류입니다.

collector server도 2.8.1 로 업데이트 하면 해결이 됩니다.
(참고로 user용 client를 업데이트 하지 않아도 오류가 발생하지는 않지만, 2.8.1에 추가된 xlog의 속성들을 보려면 client도 업데이트를 해야 합니다.)

**Comment by lu8300test** [comment]
> 안녕하세요.
> 
> collector server 버전은 java agent 버전과 같거나 더 상위 버전이어야 합니다.
> 2.8.1에 새롭게 정의된 pack type 27을 collector server가 파싱할 수 없어 발생하는 오류입니다.
> 
> collector server도 2.8.1 로 업데이트 하면 해결이 됩니다.
> (참고로 user용 client를 업데이트 하지 않아도 오류가 발생하지는 않지만, 2.8.1에 추가된 xlog의 속성들을 보려면 client도 업데이트를 해야 합니다.)

감사합니다.
lib폴더에 이전 server가 남이 있어서 2.7.1버전으로 실행이 되었었네요. 잘 해결되었습니다.
