### ISSUE TITLE
xlog profile이 보이지 않는 현상 ( No xlog profile collected )

### ISSUE THREAD

**Issue by hohosyk** [scouter-project/scouter#716]
안녕하세요~ 스카우터 초보입니다. 
모니터링하면서, 잘 사용하고 있습니다. 

시스템에 적용시, 종종 스카우터 용량이 차면서
xlog profile이 안나오는 현상을 막아보고자, 

Config Server를 하기처럼 변경하고
mgr_purge_disk_usage_pct=50
mgr_purge_profile_keep_days=5
mgr_purge_xlog_keep_days=5
mgr_purge_xlog_without_profile_keep_days=15

Scouter 서버의 용량을 50%가 안넘어가도록, 30% 이하로 맞추려고 설정하여 사용중입니다. 

=============================================================
그런데... 오늘(7/13) 로그를 점검하려다 어제자 (7/12) xlog의 profile이  안보여서요

------------------------------------------------------------------------------------------
    p#      #    	  TIME         T-GAP   CPU          CONTENTS
------------------------------------------------------------------------------------------

                     ( No xlog profile collected ) 

scouter 서버의 용량은 30%였습니다. 
어제자 경로인 /database/20200712/xlog에 
xlog.profile이 삭제되어있더라구요. 

설정을  봐보면 하기과 같고
/database/20200712/xlog:> cat xlog.profile.conf
-- listing properties --
compress_profile_enabled=false

/database/20200712/xlog:> cat xlog.service.conf
-- listing properties --
compress_xlog_enabled=false

server의 nohup.out 로그를 보니 하기와 같던데...
혹시 어떤 설정을 더 해주어야  xlog profile이 삭제가 안될까요? 

12:10:10.146 [scouter.server.http.HttpServer]  INFO  org.eclipse.jetty.server.session[149] - Scavenging every 600000ms
 12:10:10.811 [XLogThread-127.0.0.1:6001-0]  INFO  s.w.framework.client.net.ClientTCP[62] - Connected scouterx.webapp.framework.client.net.ClientTCP@4bb8a352 to 127.0.0.1:6001
 12:10:11.503 [scouter.server.http.HttpServer]  INFO  o.h.validator.internal.util.Version[27] - HV000001: Hibernate Validator 5.1.3.Final
 12:10:11.765 [scouterx.webapp.framework.client.server.ServerManager]  INFO  s.w.framework.client.net.ClientTCP[62] - Connected scouterx.webapp.framework.client.net.ClientTCP@49a77b08 to 127.0.0.1:6001
 12:10:11.812 [XLogThread-127.0.0.1:6001-0]  INFO  s.w.framework.client.net.ClientTCP[62] - Connected scouterx.webapp.framework.client.net.ClientTCP@4696a7c3 to 127.0.0.1:6001
 12:10:12.019 [scouter.server.http.HttpServer]  INFO  org.reflections.Reflections[232] - Reflections took 82 ms to scan 1 urls, producing 290 keys and 394 values
 12:10:12.446 [scouter.server.http.HttpServer]  INFO  o.e.j.server.handler.ContextHandler[788] - Started o.e.j.s.ServletContextHandler@6cf3a62f{/,null,AVAILABLE}
 12:10:12.458 [scouter.server.http.HttpServer]  INFO  o.e.jetty.server.AbstractConnector[280] - Started ServerConnector@45e70612{HTTP/1.1,[http/1.1]}{0.0.0.0:5001}
 12:10:12.459 [scouter.server.http.HttpServer]  INFO  org.eclipse.jetty.server.Server[444] - Started @5531ms
java.lang.RuntimeException: java.io.EOFException
        at scouter.server.db.text.TextPermData.read(TextPermData.scala:91)
        at scouter.server.db.TextPermRD$.getString(TextPermRD.scala:37)
        at scouter.server.db.TextRD$.getString(TextRD.scala:35)
        at scouter.server.netio.service.handle.HashText$$anonfun$getText100$1.apply$mcVI$sp(HashText.scala:78)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
        at scouter.server.netio.service.handle.HashText.getText100(HashText.scala:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scouter.server.netio.service.ServiceHandlingProxy$Invocation.exec(ServiceHandlingProxy.java:42)
        at scouter.server.netio.service.ServiceHandlingProxy.process(ServiceHandlingProxy.java:101)
        at scouter.server.netio.service.net.ServiceWorker.run(TcpServiceWorker.scala:126)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
        at java.io.RandomAccessFile.readInt(RandomAccessFile.java:803)
        at scouter.server.db.text.TextPermData.read(TextPermData.scala:85)
        ... 15 more
java.lang.RuntimeException: java.io.EOFException
        at scouter.server.db.text.TextPermData.read(TextPermData.scala:91)
        at scouter.server.db.TextPermRD$.getString(TextPermRD.scala:37)
        at scouter.server.db.TextRD$.getString(TextRD.scala:35)
        at scouter.server.netio.service.handle.HashText$$anonfun$getText100$1.apply$mcVI$sp(HashText.scala:78)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
        at scouter.server.netio.service.handle.HashText.getText100(HashText.scala:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scouter.server.netio.service.ServiceHandlingProxy$Invocation.exec(ServiceHandlingProxy.java:42)
        at scouter.server.netio.service.ServiceHandlingProxy.process(ServiceHandlingProxy.java:101)
        at scouter.server.netio.service.net.ServiceWorker.run(TcpServiceWorker.scala:126)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
        at java.io.RandomAccessFile.readInt(RandomAccessFile.java:803)
        at scouter.server.db.text.TextPermData.read(TextPermData.scala:85)
        ... 15 more
java.lang.RuntimeException: java.io.EOFException
        at scouter.server.db.text.TextPermData.read(TextPermData.scala:91)
        at scouter.server.db.TextPermRD$.getString(TextPermRD.scala:37)
        at scouter.server.db.TextRD$.getString(TextRD.scala:35)
        at scouter.server.netio.service.handle.HashText$$anonfun$getText100$1.apply$mcVI$sp(HashText.scala:78)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
        at scouter.server.netio.service.handle.HashText.getText100(HashText.scala:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scouter.server.netio.service.ServiceHandlingProxy$Invocation.exec(ServiceHandlingProxy.java:42)
        at scouter.server.netio.service.ServiceHandlingProxy.process(ServiceHandlingProxy.java:101)
        at scouter.server.netio.service.net.ServiceWorker.run(TcpServiceWorker.scala:126)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
        at java.io.RandomAccessFile.readInt(RandomAccessFile.java:803)
        at scouter.server.db.text.TextPermData.read(TextPermData.scala:85)
        ... 15 more

**Comment by gunlee01** [comment]
디스크 사용량이 50%를 넘어서서 전일의 profile이 삭제된건 아닌가요?
하루에 쌓이는 용량이 얼마인지 확인해보세요.
mgr_purge_disk_usage_pct=50
설정이면 디스크 사용량이 50%를 넘어가면 과거 데이터 부터 삭제합니다.

**Comment by hohosyk** [comment]
확인해보겠습니다.감사합니다.
