### ISSUE TITLE
scouter agent.java thread-pool 오류 문의

### ISSUE THREAD

**Issue by redutan** [scouter-project/scouter#719]
안녕하세요. 스카우터 agent.java에서 thread-pool 오류가 발생해서 문의드려요.

아래와 같은 stacktrace와 함께 오류가 발생하고 있습니다.
보니까 스카우터 내부에서 사용하는 thread-pool 이 부족한 것 같은데요. 
혹시나 해서 설정을 찾아보았지만 해당 스레드 풀 갯수를 늘릴 수 있는 방안은 찾지 못해서 문의 드려 봅니다.
* 아니면 다른 해결 방안이 있어도 좋을 것 같습니다.

고맙습니다.

```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@3873f5c6 rejected from java.util.concurrent.ThreadPoolExecutor@63a43389[Running, pool size = 40, active threads = 40, queued tasks = 40, completed tasks = 64644]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.submit(ThreadPoolTaskExecutor.java:341)
Summary  |  다운로드
```

**Comment by gunlee01** [comment]
scouter agent 쪽의 thread pool은 아닐 것 같은데 좀 더 상세한 정보가 있을까요?
일단 agent에서는 thread pool을 자체 구형하고 있고, ThreadPoolExecutor 로 생성하는 thread pool은 없는걸로 알고 있습니다. 

scouter.agent.wrapper.async.WrTaskCallable 클래스는 비동기 추적을 위해 submit에 Callable이 넘어갈 때 scouter가 callable을 wrapping 하는 클래스입니다.

**Comment by redutan** [comment]
@gunlee01 
아 답변 고맙습니다.

내부에서 사용하는 스레드 중 하나인 것 같은데, 혹시 스카우터 내부에서 사용하는 스레드인가? 의심하는 상황이었는데,
WrTaskCallable 클래스가 추적을 위한 Wrapper라면 제가 직접 문제의 답을 찾으면 될 것 같습니다.

답변 고맙습니다. :)

**Comment by gunlee01** [comment]
This issue has been open for more than a year without recent activity. Closing due to lack of response. If you believe this issue is still relevant, please feel free to reopen it at any time. We are here to help!

---
*Note: This action was generated by AI agent. / 참고: 이 작업은 AI 에이전트에 의해 생성되었습니다.*
