### ISSUE TITLE
java.lang.NullPointerException on Mac Os BigSur

### ISSUE THREAD

**Issue by keeneye7** [scouter-project/scouter#755]
BigSur 업데이트 후 scouter client 실행시 NullPointException이 발생하고 있습니다.

.scouter/.meta/.log
`eclipse.buildId=unknown
java.version=1.8.0_261
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_KR
Framework arguments:  -keyring /Users/keeneye7/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data @user.home/.scouter -keyring /Users/keeneye7/.eclipse_keyring

!ENTRY org.eclipse.osgi 4 0 2020-09-28 15:06:34.523
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
        at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2180)
        at org.eclipse.swt.graphics.GC.<init>(GC.java:177)
        at org.eclipse.swt.graphics.GC.<init>(GC.java:138)
        at org.eclipse.jface.dialogs.Dialog.initializeDialogUnits(Dialog.java:937)
        at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:769)
        at org.eclipse.jface.window.Window.create(Window.java:429)
        at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1099)
        at org.eclipse.jface.window.Window.open(Window.java:786)
        at scouter.client.Application.openLoginDialog(Application.java:97)
        at scouter.client.Application.start(Application.java:76)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1501)`

다른 어플리케이션에서도 비슷한 사례가 있어 링크 보내드립니다.
https://forum.portfolio-performance.info/t/java-lang-nullpointerexception-on-mac-os-big-sur/9884

**Comment by showtime926** [comment]
저도 bigsur에서 같은 증상입니다.

**Comment by gunlee01** [comment]
Scouter RCP가 오래된 컴포넌트들에 대한 의존성이 많아 BigSur 이슈는 해결에 시간이 걸릴 것 같습니다.

**Comment by anisia20** [comment]
저 같은 경우 gcc 재 설치로 해결 했습니다. 
brew 최신 버전 필요
brew reinstall gcc

**Comment by showtime926** [comment]
안녕하세요.

 

말씀하신대로 gcc 재설치 후 정상적으로 사용가능 해졌습니다.

너무 너무 너무 감사드립니다. 😊

**Comment by gunlee01** [comment]
빅서에서 java 경로 명시등을 통해 클라이언트 실행은 가능하지만 컴포넌트 및 렌더링등이 제대로 지원되지 않으면서 올바로 작동하지 않습니다.

xlog 조회 및 드래그, 상세 프로필 조회, 윈도우 사이즈 변경등도 잘 되시나요?

**Comment by showtime926** [comment]
네 java 경로 수정해서 처음 실행 했을 땐 잘 되는 것처럼 보였는데, 

사용해보니 말씀하신 문제들이 계속 있습니다.

결국 다시 windows vm 으로 사용하고 있습니다.

감사합니다.

**Comment by gunlee01** [comment]
Scouter will support Big Sur on the version 2.15.0
