### ISSUE TITLE
JDK 13 사용시 Unsupported class file major version 57 문제 해결 하신분 계신가요 ? 

### ISSUE THREAD

**Issue by jiman94** [scouter-project/scouter#780]
-javaagent:/Users/mz03-jmryu/Project/demo-env1/scouter.agent.jar -Dscouter.config=/Users/mz03-jmryu/Project/demo-env1/conf/scouter.conf

  ____                  _            
 / ___|  ___ ___  _   _| |_ ___ _ __ 
 \___ \ / __/   \| | | | __/ _ \ '__|
  ___) | (_| (+) | |_| | ||  __/ |   
 |____/ \___\___/ \__,_|\__\___|_|                                      
 Open Source S/W Performance Monitoring  
 Scouter version 2.6.2
 
20210205 10:45:01 [SCOUTER] Version 2.6.2 2019-04-28 13:41 GMT_ENV_java8plus
20210205 10:45:01 [SCOUTER] loaded by system classloader 
20210205 10:45:01 [SCOUTER] jar:file:/Users/mz03-jmryu/Project/demo-env1/scouter.agent.jar
20210205 10:45:01 [A101] Transformer Error : java/util/concurrent/ThreadPoolExecutor
20210205 10:45:01 [A101] Transformer Error : oss/pilot/performance/Application
java.lang.IllegalArgumentException: Unsupported class file major version 57
	scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
	scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	scouter.agent.AgentTransformer.transform(AgentTransformer.java:207)
	java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	java.instrument/sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	java.instrument/sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:193)
	scouter.agent.util.AsyncRunner.hooking(AsyncRunner.java:204)
	scouter.agent.util.AsyncRunner.run(AsyncRunner.java:94)
java.lang.IllegalArgumentException: Unsupported class file major version 57
java.lang.IllegalArgumentException: Unsupported class file major version 57
	scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
	scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	scouter.agent.AgentTransformer.transform(AgentTransformer.java:207)
	java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	java.base/java.lang.ClassLoader.defineClass1(Native Method)
	java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	java.base/java.lang.Class.forName0(Native Method)
	java.base/java.lang.Class.forName(Class.java:416)
	java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:760)
	java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)
	at scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
	at scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	at scouter.agent.AgentTransformer.transform(AgentTransformer.java:207)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:193)
	at scouter.agent.util.AsyncRunner.hooking(AsyncRunner.java:204)
	at scouter.agent.util.AsyncRunner.run(AsyncRunner.java:94)
java.lang.IllegalArgumentException: Unsupported class file major version 57
	at scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
	at scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at scouter.org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	at scouter.agent.AgentTransformer.transform(AgentTransformer.java:207)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:760)

**Comment by gunlee01** [comment]
최신 버전 agent(2.10)으로 사용해 보시기 바랍니다. 
2.10 릴리즈 노트에 java 14 지원, 2.6 릴리즈 노트에는 java version 11을 지원하는 것으로 되어 있습니다.
