### ISSUE TITLE
Unable to save xlog profile in Windows

### ISSUE THREAD

**Issue by alqa-dash** [scouter-project/scouter#796]
Unable to save xlog profile with following exception:

[XLog] 1 selected.
java.io.FileNotFoundException: C:\Users\user\scouter\app02\20210517\app02\ais\xlog\[001-102630]x70un0ln0irc5f__api_ases<GET>\xlog.prof (The filename, directory name, or volume label syntax is incorrect)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
	at scouter.client.xlog.SaveProfileJob.saveFullProfile(SaveProfileJob.java:173)
	at scouter.client.xlog.SaveProfileJob.run(SaveProfileJob.java:92)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
java.io.FileNotFoundException: C:\Users\user\scouter\app02\20210517\app02\ais\xlog\[001-102630]x70un0ln0irc5f__api_ases<GET>\xlog.xlog (The filename, directory name, or volume label syntax is incorrect)
Timer Start
Notice Response Code : 200

**Comment by gunlee01** [comment]
resolving for next version
