### ISSUE TITLE
윈도우 클라이언트 java version 문의

### ISSUE THREAD

**Issue by codingstore** [scouter-project/scouter#824]
안녕하세요 
이번에 릴리즈된 2.15.0버전으로 스카우터 클라이언트를 설치하였습니다.
https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Setup.md
scouter client for Mac needs Java11+
맥 버전에서는 java11+가 필요하다고 기술되어 있습니다.

jdk1.8이 설치된 윈도우에서 2.15.0버전 클라이언트 실행 시 에러가 발생하며 아래와 같은 로그가 남았습니다.
(2.12.0.1의 클라이언트는 정상적으로 실행이 됩니다.)
```bash
!SESSION 2021-10-05 14:11:47.913 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_281
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ko_KR
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data @user.home/scouter

!ENTRY org.eclipse.core.runtime 4 0 2021-10-05 14:11:50.299
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.core.runtime [34]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
  Unresolved requirement: Require-Bundle: org.eclipse.equinox.registry; bundle-version="[3.10.0,4.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.equinox.registry; bundle-version="3.11.0.v20210723-1953"; singleton:="true"
       org.eclipse.equinox.registry [73]
         Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.14.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.15.0.v20210518-0604"; singleton:="true"
              org.eclipse.equinox.common [67]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
         Unresolved requirement: Import-Package: org.eclipse.core.runtime.jobs; resolution:="optional"
           -> Export-Package: org.eclipse.core.runtime.jobs; bundle-symbolic-name="org.eclipse.core.jobs"; bundle-version="3.12.0.v20210723-1034"; version="0.0.0"
              org.eclipse.core.jobs [32]
                Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.8.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.15.0.v20210518-0604"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.core.jobs; bundle-version="[3.10.0,4.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.core.jobs; bundle-version="3.12.0.v20210723-1034"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.14.0,4.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.15.0.v20210518-0604"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.core.contenttype; bundle-version="[3.7.0,4.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.core.contenttype; bundle-version="3.8.0.v20210621-0954"; singleton:="true"
       org.eclipse.core.contenttype [25]
         Unresolved requirement: Require-Bundle: org.eclipse.equinox.preferences; bundle-version="[3.2.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.equinox.preferences; bundle-version="3.9.0.v20210726-0943"; singleton:="true"
              org.eclipse.equinox.preferences [72]
                Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.2.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.15.0.v20210518-0604"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.equinox.app; bundle-version="1.3.0"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.equinox.app; bundle-version="1.6.0.v20210723-1130"; singleton:="true"
       org.eclipse.equinox.app [65]
         Unresolved requirement: Require-Bundle: org.eclipse.equinox.registry; bundle-version="[3.4.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.equinox.registry; bundle-version="3.11.0.v20210723-1953"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.equinox.preferences; bundle-version="[3.7.0,4.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.equinox.preferences; bundle-version="3.9.0.v20210726-0943"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1777)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

!ENTRY org.eclipse.compare.core 4 0 2021-10-05 14:11:50.299
!MESSAGE FrameworkEvent ERROR

```

jre 11이 필요하다는 내용으로 보여서 scouter.ini에서 jdk11을 바라보도록 아래의 내용을 추가해주었습니다
```bash
-vm
C:\openjdk\java-11-openjdk-11.0.12.7-1.windows.ojdkbuild.x86_64\bin\javaw.exe
```
일단 정상적으로 기동이 되는것은 확인하였습니다.

윈도우용 스카우터 클라이언트도 java11이 필요하도록 변경된것인가요?

**Comment by gunlee01** [comment]
eclipse 버전이 올라가서 OS 무관하게 java 11이 필요합니다. 
해당 내용은 보강해 놓겠습니다.

**Comment by gunlee01** [comment]
This issue has been open for more than a year without recent activity. Closing due to lack of response. If you believe this issue is still relevant, please feel free to reopen it at any time. We are here to help!

---
*Note: This action was generated by AI agent. / 참고: 이 작업은 AI 에이전트에 의해 생성되었습니다.*
