### ISSUE TITLE
tomcat8.5.75 / jdk1.7 환경에서 적용이 되지 않는 현상

### ISSUE THREAD

**Issue by Neptunium1129** [scouter-project/scouter#844]
![image](https://user-images.githubusercontent.com/32185134/151956597-d0f77adc-0cf9-42bc-b91f-ee28fcb6e74b.png)

![image](https://user-images.githubusercontent.com/32185134/151956704-c36ab071-6ada-44ab-aa64-8926cdff9e31.png)

에이전트는 6.7 꺼를 사용했습니다.

jdk 에이전트는 버전에 상관없다고 댓글로 보여지는데 작동이 안되는것 같습니다.

 Caused by: java.lang.NoClassDefFoundError: scouter/agent/trace/TraceMain
                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java)
                at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:994)
                at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)

**Comment by Neptunium1129** [comment]
2.5.1로 다운그레이드하면 아래와 같은 오류가 발생합니다.
![image](https://user-images.githubusercontent.com/32185134/152134352-c0097172-4e29-426e-a51f-011665da266b.png)
