### ISSUE TITLE
리포트 (java) 생성 불가 현상 관련 문의드립니다. 

### ISSUE THREAD

**Issue by eltit2022** [scouter-project/scouter#864]
안녕하세요, Scouter 리포트 기능을 유용하게 사용중이 었는데, 
어느날부터 리포트(java) 생성이 불가능 합니다.

리포트 실행하면 아래와  같이 메세지가 출력되며 java 리포트 생성이 되지가 않네요. 

-----------------------------------------------------------------------------------------------
[SCOUTER-X] Start Daily Host Report.
**[SCOUTER-X] Start Daily Java Report.
java.lang.IllegalArgumentException: The workbook already contains a sheet of this name
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.setSheetName(XSSFWorkbook.java:1581)
        at scouter.plugin.server.reporting.report.JavaReport.createExcel(JavaReport.java:60)
        at scouter.plugin.server.reporting.ReportingPlugin.main(ReportingPlugin.java:1050)**
[SCOUTER-X] Start Daily Service Report.
-----------------------------------------------------------------------------------------------

얼마전에 신규 인스턴스를 기존 Scouter에 등록헀습니다. 
등록할때 신규 인스턴스 Object 명이 Scouter에 물려있는 인스턴스와  동일하게 설정을 했는데,  해당부분은 확인하고 신규 object 명은 다른거로 바로 수정했고요. 

그런데 scouter DB에서 중복된 object 값을 가지고 있어서 리포트 생성이 안되는건 아닌지.. 
하는 생각은 드네요. 
관련하여 도움 부탁드리겠습니다.

- 이슈관련 조치 한사항 
1) 신규 인스턴스 object 네임 변경 ( 기존 인스턴스와 object명 중복 방지 )
2) Scouter Server, Agent, 재 기동

**Comment by gunlee01** [comment]
SCOUTER-X 쪽은 오픈소스컨설팅에서 만드신걸로 기억이 되는데 그 쪽으로 연락해 보시기 바랍니다.
