### ISSUE TITLE
zipkin request 발생 시, 간헐적으로 collector에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by kwonssy02** [scouter-project/scouter#871]
안녕하세요.
zipkin request 발생 시 collector에서 아래와 같은 에러가 간헐적으로 발생하는데, 어떤 현상인지 알 수 있을까요?

```java
java.io.IOException: Stream Closed
        at java.io.RandomAccessFile.writeBytes(Native Method)
        at java.io.RandomAccessFile.write(RandomAccessFile.java:512)
        at scouter.server.db.io.RealKeyFile.write(RealKeyFile.scala:111)
        at scouter.server.db.io.RealKeyFile.append(RealKeyFile.scala:134)
        at scouter.server.db.io.IndexKeyFile.put(IndexKeyFile.scala:61)
        at scouter.server.db.span.ZipkinSpanIndex.setByGxid(ZipkinSpanIndex.scala:64)
        at scouter.server.db.ZipkinSpanWR$$anonfun$2.apply$mcV$sp(ZipkinSpanWR.scala:75)
        at scouter.server.util.ThreadScala$$anon$4.run(ThreadScala.scala:64)
```

**Comment by gunlee01** [comment]
This issue has been open for more than a year without recent activity. Closing due to lack of response. If you believe this issue is still relevant, please feel free to reopen it at any time. We are here to help!

---
*Note: This action was generated by AI agent. / 참고: 이 작업은 AI 에이전트에 의해 생성되었습니다.*
