### ISSUE TITLE
스카우터 자바 Path 설정 문의

### ISSUE THREAD

**Issue by maseunguk** [scouter-project/scouter#895]
안녕하세요. 

담당하는 시스템 개발 환경에 스카우터 적용하려고 하니 하기 St메세지 발생하여 대상 서버에 깔려 있는 1.8JDK로 

자바 Path를 바꿔 주고 싶은데 어떤 경로의 파일을 수정 하면 되는지 알고 싶어 문의 드립니다.

그리고 이게 올바른 방법인지도 문의 드립니다. 해당 시스템 개발 환경에 제가 맡은 시스템 말고도 다른 시스템들이 올라와 있어

해당 방식으로 진행 하려 하고 있습니다.

설치 JAVA 버전 
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

설치 자바 경로
/usr/java/jdk1.8.0_202/bin

startup.sh 수행 시 발생 메세지
nohup: redirecting stderr to stdout
Exception in thread "main" java.lang.UnsupportedClassVersionError: scouter/boot/Boot : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: scouter.boot.Boot.  Program will exit.

**Comment by maseunguk** [comment]
참고로 현재 설치 하고자 하는 Scouter 버전은 2.17.1 버전입니다.

**Comment by zbum** [comment]
@maseunguk 스카우터 클라이언트는 현재 java 11 버전 이상에서 동작합니다.
