### ISSUE TITLE
scouter weaver not working

### ISSUE THREAD

**Issue by qeorbn** [scouter-project/scouter#899]
Env:
SpringBoot 2.1.9.RELEASE.
Scouter agent version : 2.10.2
Maven dependency : scouter-weaver:2.17.1

I can't get the txid with Scouter.getTxidOnTheSameThread().
Also, Scouter.isScouterJavaAgentActivated() return false.
But, the scouter agent work well and I can see the request in xlog.

Is there any configuration missing?

@gunlee01

**Comment by qeorbn** [comment]
@gunlee01 
회신을 기대

**Comment by gunlee01** [comment]
try ro use the same version of scouter agent and the weaver.

**Comment by qeorbn** [comment]
thks. It worked. @gunlee01 
Another question: I can't find the api of get gxid,  is there any way to log gxid ?

**Comment by qeorbn** [comment]
**java.lang.NullPointerException: null
        at scouterx.weaver.Scouter$Weaving.getTxidOnTheSameThread(Scouter.java:624)
        at scouterx.weaver.Scouter.getTxidOnTheSameThread(Scouter.java:353)**

I got this error in another machine ,but I have the same agent\server\app\java version...

SpringBoot 2.1.9.RELEASE.
Scouter agent version : 2.17.1
Maven dependency : scouter-weaver:2.17.1

@gunlee01  plz help

**Comment by qeorbn** [comment]
I can't find the difference about these two java agent .
Is it related to scouter server ? @gunlee01

**Comment by gunlee01** [comment]
[scouter.agent.jar.zip](https://github.com/scouter-project/scouter/files/9967224/scouter.agent.jar.zip)
No. it's only related with java agent. Can you check it with this java agent?

**Comment by qeorbn** [comment]
> [scouter.agent.jar.zip](https://github.com/scouter-project/scouter/files/9967224/scouter.agent.jar.zip) No. it's only related with java agent. Can you check it with this java agent?

still not working.
I got the same error  with the new agent.jar
@gunlee01
