### ISSUE TITLE
특정 일자 xlog 히스토리 로딩 안됨

### ISSUE THREAD

**Issue by mspark7233** [scouter-project/scouter#993]
scouter agent 버전 : 2.10.0
scouter 수집 서버 버전 : 2.10.0
scouter 수집 Java 버전: 1.8.0_181

해당 일자의 히스토리 로딩 시 수집 서버에서 아래의 메세지 발생 합니다.

java.lang.RuntimeException: Unknown pack type= 0
        at scouter.lang.pack.PackEnum.create(PackEnum.java:62)
        at scouter.io.DataInputX.readPack(DataInputX.java:268)
        at scouter.server.db.ObjectRD$$anonfun$getObjectList$1.apply(ObjectRD.scala:82)
        at scouter.server.db.ObjectRD$$anonfun$getObjectList$1.apply(ObjectRD.scala:80)
        at scouter.server.db.io.IndexKeyFile.read(IndexKeyFile.scala:197)
        at scouter.server.db.obj.ObjectIndex.read(ObjectIndex.scala:76)
        at scouter.server.db.ObjectRD$.read(ObjectRD.scala:109)
        at scouter.server.db.ObjectRD$.getObjectList(ObjectRD.scala:80)
        at scouter.server.db.ObjectRD$.getDailyAgent(ObjectRD.scala:61)
        at scouter.server.netio.service.handle.AgentInfo.getAgentOldList(AgentInfo.scala:72)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scouter.server.netio.service.ServiceHandlingProxy$Invocation.exec(ServiceHandlingProxy.java:42)
        at scouter.server.netio.service.ServiceHandlingProxy.process(ServiceHandlingProxy.java:101)
        at scouter.server.netio.service.net.ServiceWorker.run(TcpServiceWorker.scala:126)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

원인과 해결 방법을 알 수 있을까요?

**Comment by gunlee01** [comment]
This issue has been open for more than a year without recent activity. Closing due to lack of response. If you believe this issue is still relevant, please feel free to reopen it at any time. We are here to help!

---
*Note: This action was generated by AI agent. / 참고: 이 작업은 AI 에이전트에 의해 생성되었습니다.*
